language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install jupyter
  - pip install pandas
  - pip install numpy
script:
  - jupyter nbconvert --to html water_resource_challenge.ipynb
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
